services:
  orthanc:
    image: jodogne/orthanc-plugins:latest
    command: /etc/orthanc
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro # orthanc.json 볼륨 설정
      - ./orthanc-db:/var/lib/orthanc/db # dicom 파일 볼륨 설정
    environment:
      - ORTHANC_NAME=HelloWorld
